apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app.kubernetes.io/name: blaxsmith-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: blaxsmith-app
    app.kubernetes.io/instance: {{ .Release.Name }}
