apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
  labels:
    app.kubernetes.io/name: blaxsmith-preview
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: blaxsmith-preview
    app.kubernetes.io/instance: {{ .Release.Name }}
