/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as AdminRecipesIndexRouteImport } from './routes/admin.recipes.index'
import { Route as AdminRecipesNewRouteImport } from './routes/admin.recipes.new'
import { Route as ProjectsProjectIdModelAccessRouteImport } from './routes/projects.$projectId.model-access'
import { Route as ProjectsProjectIdSourceRouteImport } from './routes/projects.$projectId.source'
import { Route as ProjectsProjectIdVerificationRouteImport } from './routes/projects.$projectId.verification'
import { Route as AdminRecipesRecipeIdIndexRouteImport } from './routes/admin.recipes.$recipeId.index'
import { Route as ProjectsProjectIdModelAccessNewRouteImport } from './routes/projects.$projectId.model-access.new'
import { Route as ProjectsProjectIdRecipesIndexRouteImport } from './routes/projects.$projectId.recipes.index'
import { Route as ProjectsProjectIdRecipesNewRouteImport } from './routes/projects.$projectId.recipes.new'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects.$projectId.runs.$runId'
import { Route as ProjectsProjectIdRunsNewRouteImport } from './routes/projects.$projectId.runs.new'
import { Route as AdminRecipesRecipeIdVersionsNewRouteImport } from './routes/admin.recipes.$recipeId.versions.new'
import { Route as ProjectsProjectIdRecipesRecipeIdIndexRouteImport } from './routes/projects.$projectId.recipes.$recipeId.index'
import { Route as ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport } from './routes/projects.$projectId.recipes.$recipeId.versions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesIndexRoute = AdminRecipesIndexRouteImport.update({
  id: '/admin/recipes/',
  path: '/admin/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/admin/recipes/new',
  path: '/admin/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdModelAccessRoute =
  ProjectsProjectIdModelAccessRouteImport.update({
    id: '/model-access',
    path: '/model-access',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSourceRoute = ProjectsProjectIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVerificationRoute =
  ProjectsProjectIdVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AdminRecipesRecipeIdIndexRoute =
  AdminRecipesRecipeIdIndexRouteImport.update({
    id: '/admin/recipes/$recipeId/',
    path: '/admin/recipes/$recipeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdModelAccessNewRoute =
  ProjectsProjectIdModelAccessNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdModelAccessRoute,
  } as any)
const ProjectsProjectIdRecipesIndexRoute =
  ProjectsProjectIdRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRecipesNewRoute =
  ProjectsProjectIdRecipesNewRouteImport.update({
    id: '/recipes/new',
    path: '/recipes/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsNewRoute =
  ProjectsProjectIdRunsNewRouteImport.update({
    id: '/runs/new',
    path: '/runs/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AdminRecipesRecipeIdVersionsNewRoute =
  AdminRecipesRecipeIdVersionsNewRouteImport.update({
    id: '/admin/recipes/$recipeId/versions/new',
    path: '/admin/recipes/$recipeId/versions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRecipesRecipeIdIndexRoute =
  ProjectsProjectIdRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRecipesRecipeIdVersionsNewRoute =
  ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport.update({
    id: '/recipes/$recipeId/versions/new',
    path: '/recipes/$recipeId/versions/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId/': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/recipes/$recipeId/': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/recipes': typeof AdminRecipesIndexRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/recipes/$recipeId': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId/': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/recipes/$recipeId/': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/admin/'
    | '/admin/recipes/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/recipes/'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId/'
    | '/projects/$projectId/recipes/'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/recipes/$recipeId/'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/admin'
    | '/admin/recipes/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/recipes'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId'
    | '/projects/$projectId/recipes'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/recipes/$recipeId'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/admin/'
    | '/admin/recipes/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/recipes/'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId/'
    | '/projects/$projectId/recipes/'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/recipes/$recipeId/'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ToolsRoute: typeof ToolsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminRecipesIndexRoute: typeof AdminRecipesIndexRoute
  AdminRecipesRecipeIdIndexRoute: typeof AdminRecipesRecipeIdIndexRoute
  AdminRecipesRecipeIdVersionsNewRoute: typeof AdminRecipesRecipeIdVersionsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/': {
      id: '/admin/recipes/'
      path: '/admin/recipes'
      fullPath: '/admin/recipes/'
      preLoaderRoute: typeof AdminRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/admin/recipes/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/model-access': {
      id: '/projects/$projectId/model-access'
      path: '/model-access'
      fullPath: '/projects/$projectId/model-access'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/source': {
      id: '/projects/$projectId/source'
      path: '/source'
      fullPath: '/projects/$projectId/source'
      preLoaderRoute: typeof ProjectsProjectIdSourceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/verification': {
      id: '/projects/$projectId/verification'
      path: '/verification'
      fullPath: '/projects/$projectId/verification'
      preLoaderRoute: typeof ProjectsProjectIdVerificationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/admin/recipes/$recipeId/': {
      id: '/admin/recipes/$recipeId/'
      path: '/admin/recipes/$recipeId'
      fullPath: '/admin/recipes/$recipeId/'
      preLoaderRoute: typeof AdminRecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/model-access/new': {
      id: '/projects/$projectId/model-access/new'
      path: '/new'
      fullPath: '/projects/$projectId/model-access/new'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessNewRouteImport
      parentRoute: typeof ProjectsProjectIdModelAccessRoute
    }
    '/projects/$projectId/recipes/': {
      id: '/projects/$projectId/recipes/'
      path: '/recipes'
      fullPath: '/projects/$projectId/recipes/'
      preLoaderRoute: typeof ProjectsProjectIdRecipesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/recipes/new': {
      id: '/projects/$projectId/recipes/new'
      path: '/recipes/new'
      fullPath: '/projects/$projectId/recipes/new'
      preLoaderRoute: typeof ProjectsProjectIdRecipesNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/new': {
      id: '/projects/$projectId/runs/new'
      path: '/runs/new'
      fullPath: '/projects/$projectId/runs/new'
      preLoaderRoute: typeof ProjectsProjectIdRunsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/admin/recipes/$recipeId/versions/new': {
      id: '/admin/recipes/$recipeId/versions/new'
      path: '/admin/recipes/$recipeId/versions/new'
      fullPath: '/admin/recipes/$recipeId/versions/new'
      preLoaderRoute: typeof AdminRecipesRecipeIdVersionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/recipes/$recipeId/': {
      id: '/projects/$projectId/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/projects/$projectId/recipes/$recipeId/'
      preLoaderRoute: typeof ProjectsProjectIdRecipesRecipeIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/recipes/$recipeId/versions/new': {
      id: '/projects/$projectId/recipes/$recipeId/versions/new'
      path: '/recipes/$recipeId/versions/new'
      fullPath: '/projects/$projectId/recipes/$recipeId/versions/new'
      preLoaderRoute: typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdModelAccessRouteChildren {
  ProjectsProjectIdModelAccessNewRoute: typeof ProjectsProjectIdModelAccessNewRoute
}

const ProjectsProjectIdModelAccessRouteChildren: ProjectsProjectIdModelAccessRouteChildren =
  {
    ProjectsProjectIdModelAccessNewRoute: ProjectsProjectIdModelAccessNewRoute,
  }

const ProjectsProjectIdModelAccessRouteWithChildren =
  ProjectsProjectIdModelAccessRoute._addFileChildren(
    ProjectsProjectIdModelAccessRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdModelAccessRoute: typeof ProjectsProjectIdModelAccessRouteWithChildren
  ProjectsProjectIdSourceRoute: typeof ProjectsProjectIdSourceRoute
  ProjectsProjectIdVerificationRoute: typeof ProjectsProjectIdVerificationRoute
  ProjectsProjectIdRecipesNewRoute: typeof ProjectsProjectIdRecipesNewRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
  ProjectsProjectIdRunsNewRoute: typeof ProjectsProjectIdRunsNewRoute
  ProjectsProjectIdRecipesIndexRoute: typeof ProjectsProjectIdRecipesIndexRoute
  ProjectsProjectIdRecipesRecipeIdIndexRoute: typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  ProjectsProjectIdRecipesRecipeIdVersionsNewRoute: typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdModelAccessRoute:
    ProjectsProjectIdModelAccessRouteWithChildren,
  ProjectsProjectIdSourceRoute: ProjectsProjectIdSourceRoute,
  ProjectsProjectIdVerificationRoute: ProjectsProjectIdVerificationRoute,
  ProjectsProjectIdRecipesNewRoute: ProjectsProjectIdRecipesNewRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
  ProjectsProjectIdRunsNewRoute: ProjectsProjectIdRunsNewRoute,
  ProjectsProjectIdRecipesIndexRoute: ProjectsProjectIdRecipesIndexRoute,
  ProjectsProjectIdRecipesRecipeIdIndexRoute:
    ProjectsProjectIdRecipesRecipeIdIndexRoute,
  ProjectsProjectIdRecipesRecipeIdVersionsNewRoute:
    ProjectsProjectIdRecipesRecipeIdVersionsNewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ToolsRoute: ToolsRoute,
  AdminAuditRoute: AdminAuditRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminRecipesIndexRoute: AdminRecipesIndexRoute,
  AdminRecipesRecipeIdIndexRoute: AdminRecipesRecipeIdIndexRoute,
  AdminRecipesRecipeIdVersionsNewRoute: AdminRecipesRecipeIdVersionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
