/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdModelAccessRouteImport } from './routes/projects.$projectId.model-access'
import { Route as ProjectsProjectIdSourceRouteImport } from './routes/projects.$projectId.source'
import { Route as ProjectsProjectIdVerificationRouteImport } from './routes/projects.$projectId.verification'
import { Route as ProjectsProjectIdModelAccessNewRouteImport } from './routes/projects.$projectId.model-access.new'
import { Route as ProjectsProjectIdModelAccessSubscriptionRouteImport } from './routes/projects.$projectId.model-access.subscription'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects.$projectId.runs.$runId'
import { Route as ProjectsProjectIdRunsNewRouteImport } from './routes/projects.$projectId.runs.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdModelAccessRoute =
  ProjectsProjectIdModelAccessRouteImport.update({
    id: '/model-access',
    path: '/model-access',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSourceRoute = ProjectsProjectIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVerificationRoute =
  ProjectsProjectIdVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModelAccessNewRoute =
  ProjectsProjectIdModelAccessNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdModelAccessRoute,
  } as any)
const ProjectsProjectIdModelAccessSubscriptionRoute =
  ProjectsProjectIdModelAccessSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => ProjectsProjectIdModelAccessRoute,
  } as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsNewRoute =
  ProjectsProjectIdRunsNewRouteImport.update({
    id: '/runs/new',
    path: '/runs/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tools'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tools'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tools'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ToolsRoute: typeof ToolsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/model-access': {
      id: '/projects/$projectId/model-access'
      path: '/model-access'
      fullPath: '/projects/$projectId/model-access'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/source': {
      id: '/projects/$projectId/source'
      path: '/source'
      fullPath: '/projects/$projectId/source'
      preLoaderRoute: typeof ProjectsProjectIdSourceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/verification': {
      id: '/projects/$projectId/verification'
      path: '/verification'
      fullPath: '/projects/$projectId/verification'
      preLoaderRoute: typeof ProjectsProjectIdVerificationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/model-access/new': {
      id: '/projects/$projectId/model-access/new'
      path: '/new'
      fullPath: '/projects/$projectId/model-access/new'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessNewRouteImport
      parentRoute: typeof ProjectsProjectIdModelAccessRoute
    }
    '/projects/$projectId/model-access/subscription': {
      id: '/projects/$projectId/model-access/subscription'
      path: '/subscription'
      fullPath: '/projects/$projectId/model-access/subscription'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessSubscriptionRouteImport
      parentRoute: typeof ProjectsProjectIdModelAccessRoute
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/new': {
      id: '/projects/$projectId/runs/new'
      path: '/runs/new'
      fullPath: '/projects/$projectId/runs/new'
      preLoaderRoute: typeof ProjectsProjectIdRunsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdModelAccessRouteChildren {
  ProjectsProjectIdModelAccessNewRoute: typeof ProjectsProjectIdModelAccessNewRoute
  ProjectsProjectIdModelAccessSubscriptionRoute: typeof ProjectsProjectIdModelAccessSubscriptionRoute
}

const ProjectsProjectIdModelAccessRouteChildren: ProjectsProjectIdModelAccessRouteChildren =
  {
    ProjectsProjectIdModelAccessNewRoute: ProjectsProjectIdModelAccessNewRoute,
    ProjectsProjectIdModelAccessSubscriptionRoute:
      ProjectsProjectIdModelAccessSubscriptionRoute,
  }

const ProjectsProjectIdModelAccessRouteWithChildren =
  ProjectsProjectIdModelAccessRoute._addFileChildren(
    ProjectsProjectIdModelAccessRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdModelAccessRoute: typeof ProjectsProjectIdModelAccessRouteWithChildren
  ProjectsProjectIdSourceRoute: typeof ProjectsProjectIdSourceRoute
  ProjectsProjectIdVerificationRoute: typeof ProjectsProjectIdVerificationRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
  ProjectsProjectIdRunsNewRoute: typeof ProjectsProjectIdRunsNewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdModelAccessRoute:
    ProjectsProjectIdModelAccessRouteWithChildren,
  ProjectsProjectIdSourceRoute: ProjectsProjectIdSourceRoute,
  ProjectsProjectIdVerificationRoute: ProjectsProjectIdVerificationRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
  ProjectsProjectIdRunsNewRoute: ProjectsProjectIdRunsNewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ToolsRoute: ToolsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
