/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as SetupTokenRouteImport } from './routes/setup.$token'
import { Route as AdminConnectionsIndexRouteImport } from './routes/admin.connections.index'
import { Route as AdminConnectionsConnectionIdRouteImport } from './routes/admin.connections.$connectionId'
import { Route as AdminConnectionsGithubAppRouteImport } from './routes/admin.connections.github-app'
import { Route as AdminExtensionsIndexRouteImport } from './routes/admin.extensions.index'
import { Route as AdminExtensionsExtensionIdRouteImport } from './routes/admin.extensions.$extensionId'
import { Route as AdminExtensionsNewRouteImport } from './routes/admin.extensions.new'
import { Route as AdminRecipesIndexRouteImport } from './routes/admin.recipes.index'
import { Route as AdminRecipesNewRouteImport } from './routes/admin.recipes.new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersNewRouteImport } from './routes/admin.users.new'
import { Route as MeConnectionsIndexRouteImport } from './routes/me.connections.index'
import { Route as MeConnectionsConnectionIdRouteImport } from './routes/me.connections.$connectionId'
import { Route as ProjectsProjectIdModelAccessRouteImport } from './routes/projects.$projectId.model-access'
import { Route as ProjectsProjectIdSourceRouteImport } from './routes/projects.$projectId.source'
import { Route as ProjectsProjectIdVerificationRouteImport } from './routes/projects.$projectId.verification'
import { Route as AdminConnectionsNewApiKeyRouteImport } from './routes/admin.connections.new.api-key'
import { Route as AdminConnectionsNewGitRouteImport } from './routes/admin.connections.new.git'
import { Route as AdminRecipesRecipeIdIndexRouteImport } from './routes/admin.recipes.$recipeId.index'
import { Route as MeConnectionsNewApiKeyRouteImport } from './routes/me.connections.new.api-key'
import { Route as MeConnectionsNewSubscriptionRouteImport } from './routes/me.connections.new.subscription'
import { Route as ProjectsProjectIdConnectionsIndexRouteImport } from './routes/projects.$projectId.connections.index'
import { Route as ProjectsProjectIdConnectionsConnectionIdRouteImport } from './routes/projects.$projectId.connections.$connectionId'
import { Route as ProjectsProjectIdModelAccessNewRouteImport } from './routes/projects.$projectId.model-access.new'
import { Route as ProjectsProjectIdModelAccessSubscriptionRouteImport } from './routes/projects.$projectId.model-access.subscription'
import { Route as ProjectsProjectIdRecipesIndexRouteImport } from './routes/projects.$projectId.recipes.index'
import { Route as ProjectsProjectIdRecipesNewRouteImport } from './routes/projects.$projectId.recipes.new'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects.$projectId.runs.$runId'
import { Route as ProjectsProjectIdRunsNewRouteImport } from './routes/projects.$projectId.runs.new'
import { Route as AdminRecipesRecipeIdVersionsNewRouteImport } from './routes/admin.recipes.$recipeId.versions.new'
import { Route as ProjectsProjectIdConnectionsNewApiKeyRouteImport } from './routes/projects.$projectId.connections.new.api-key'
import { Route as ProjectsProjectIdConnectionsNewGitRouteImport } from './routes/projects.$projectId.connections.new.git'
import { Route as ProjectsProjectIdRecipesRecipeIdIndexRouteImport } from './routes/projects.$projectId.recipes.$recipeId.index'
import { Route as ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport } from './routes/projects.$projectId.recipes.$recipeId.versions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTokenRoute = SetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnectionsIndexRoute = AdminConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectionsConnectionIdRoute =
  AdminConnectionsConnectionIdRouteImport.update({
    id: '/connections/$connectionId',
    path: '/connections/$connectionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConnectionsGithubAppRoute =
  AdminConnectionsGithubAppRouteImport.update({
    id: '/connections/github-app',
    path: '/connections/github-app',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExtensionsIndexRoute = AdminExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtensionsExtensionIdRoute =
  AdminExtensionsExtensionIdRouteImport.update({
    id: '/extensions/$extensionId',
    path: '/extensions/$extensionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExtensionsNewRoute = AdminExtensionsNewRouteImport.update({
  id: '/extensions/new',
  path: '/extensions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesIndexRoute = AdminRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRoute,
} as any)
const MeConnectionsIndexRoute = MeConnectionsIndexRouteImport.update({
  id: '/me/connections/',
  path: '/me/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeConnectionsConnectionIdRoute =
  MeConnectionsConnectionIdRouteImport.update({
    id: '/me/connections/$connectionId',
    path: '/me/connections/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdModelAccessRoute =
  ProjectsProjectIdModelAccessRouteImport.update({
    id: '/model-access',
    path: '/model-access',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSourceRoute = ProjectsProjectIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVerificationRoute =
  ProjectsProjectIdVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AdminConnectionsNewApiKeyRoute =
  AdminConnectionsNewApiKeyRouteImport.update({
    id: '/connections/new/api-key',
    path: '/connections/new/api-key',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConnectionsNewGitRoute = AdminConnectionsNewGitRouteImport.update({
  id: '/connections/new/git',
  path: '/connections/new/git',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRecipeIdIndexRoute =
  AdminRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AdminRoute,
  } as any)
const MeConnectionsNewApiKeyRoute = MeConnectionsNewApiKeyRouteImport.update({
  id: '/me/connections/new/api-key',
  path: '/me/connections/new/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const MeConnectionsNewSubscriptionRoute =
  MeConnectionsNewSubscriptionRouteImport.update({
    id: '/me/connections/new/subscription',
    path: '/me/connections/new/subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdConnectionsIndexRoute =
  ProjectsProjectIdConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConnectionsConnectionIdRoute =
  ProjectsProjectIdConnectionsConnectionIdRouteImport.update({
    id: '/connections/$connectionId',
    path: '/connections/$connectionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModelAccessNewRoute =
  ProjectsProjectIdModelAccessNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdModelAccessRoute,
  } as any)
const ProjectsProjectIdModelAccessSubscriptionRoute =
  ProjectsProjectIdModelAccessSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => ProjectsProjectIdModelAccessRoute,
  } as any)
const ProjectsProjectIdRecipesIndexRoute =
  ProjectsProjectIdRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRecipesNewRoute =
  ProjectsProjectIdRecipesNewRouteImport.update({
    id: '/recipes/new',
    path: '/recipes/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsNewRoute =
  ProjectsProjectIdRunsNewRouteImport.update({
    id: '/runs/new',
    path: '/runs/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AdminRecipesRecipeIdVersionsNewRoute =
  AdminRecipesRecipeIdVersionsNewRouteImport.update({
    id: '/recipes/$recipeId/versions/new',
    path: '/recipes/$recipeId/versions/new',
    getParentRoute: () => AdminRoute,
  } as any)
const ProjectsProjectIdConnectionsNewApiKeyRoute =
  ProjectsProjectIdConnectionsNewApiKeyRouteImport.update({
    id: '/connections/new/api-key',
    path: '/connections/new/api-key',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConnectionsNewGitRoute =
  ProjectsProjectIdConnectionsNewGitRouteImport.update({
    id: '/connections/new/git',
    path: '/connections/new/git',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRecipesRecipeIdIndexRoute =
  ProjectsProjectIdRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRecipesRecipeIdVersionsNewRoute =
  ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport.update({
    id: '/recipes/$recipeId/versions/new',
    path: '/recipes/$recipeId/versions/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/setup/$token': typeof SetupTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connections/$connectionId': typeof AdminConnectionsConnectionIdRoute
  '/admin/connections/github-app': typeof AdminConnectionsGithubAppRoute
  '/admin/extensions/$extensionId': typeof AdminExtensionsExtensionIdRoute
  '/admin/extensions/new': typeof AdminExtensionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/me/connections/$connectionId': typeof MeConnectionsConnectionIdRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/connections/': typeof AdminConnectionsIndexRoute
  '/admin/extensions/': typeof AdminExtensionsIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/me/connections/': typeof MeConnectionsIndexRoute
  '/admin/connections/new/api-key': typeof AdminConnectionsNewApiKeyRoute
  '/admin/connections/new/git': typeof AdminConnectionsNewGitRoute
  '/me/connections/new/api-key': typeof MeConnectionsNewApiKeyRoute
  '/me/connections/new/subscription': typeof MeConnectionsNewSubscriptionRoute
  '/projects/$projectId/connections/$connectionId': typeof ProjectsProjectIdConnectionsConnectionIdRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId/': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/connections/': typeof ProjectsProjectIdConnectionsIndexRoute
  '/projects/$projectId/recipes/': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/connections/new/api-key': typeof ProjectsProjectIdConnectionsNewApiKeyRoute
  '/projects/$projectId/connections/new/git': typeof ProjectsProjectIdConnectionsNewGitRoute
  '/projects/$projectId/recipes/$recipeId/': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/setup/$token': typeof SetupTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/connections/$connectionId': typeof AdminConnectionsConnectionIdRoute
  '/admin/connections/github-app': typeof AdminConnectionsGithubAppRoute
  '/admin/extensions/$extensionId': typeof AdminExtensionsExtensionIdRoute
  '/admin/extensions/new': typeof AdminExtensionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/me/connections/$connectionId': typeof MeConnectionsConnectionIdRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/connections': typeof AdminConnectionsIndexRoute
  '/admin/extensions': typeof AdminExtensionsIndexRoute
  '/admin/recipes': typeof AdminRecipesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/me/connections': typeof MeConnectionsIndexRoute
  '/admin/connections/new/api-key': typeof AdminConnectionsNewApiKeyRoute
  '/admin/connections/new/git': typeof AdminConnectionsNewGitRoute
  '/me/connections/new/api-key': typeof MeConnectionsNewApiKeyRoute
  '/me/connections/new/subscription': typeof MeConnectionsNewSubscriptionRoute
  '/projects/$projectId/connections/$connectionId': typeof ProjectsProjectIdConnectionsConnectionIdRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/connections': typeof ProjectsProjectIdConnectionsIndexRoute
  '/projects/$projectId/recipes': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/connections/new/api-key': typeof ProjectsProjectIdConnectionsNewApiKeyRoute
  '/projects/$projectId/connections/new/git': typeof ProjectsProjectIdConnectionsNewGitRoute
  '/projects/$projectId/recipes/$recipeId': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tools': typeof ToolsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/setup/$token': typeof SetupTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connections/$connectionId': typeof AdminConnectionsConnectionIdRoute
  '/admin/connections/github-app': typeof AdminConnectionsGithubAppRoute
  '/admin/extensions/$extensionId': typeof AdminExtensionsExtensionIdRoute
  '/admin/extensions/new': typeof AdminExtensionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/me/connections/$connectionId': typeof MeConnectionsConnectionIdRoute
  '/projects/$projectId/model-access': typeof ProjectsProjectIdModelAccessRouteWithChildren
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/verification': typeof ProjectsProjectIdVerificationRoute
  '/admin/connections/': typeof AdminConnectionsIndexRoute
  '/admin/extensions/': typeof AdminExtensionsIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/me/connections/': typeof MeConnectionsIndexRoute
  '/admin/connections/new/api-key': typeof AdminConnectionsNewApiKeyRoute
  '/admin/connections/new/git': typeof AdminConnectionsNewGitRoute
  '/me/connections/new/api-key': typeof MeConnectionsNewApiKeyRoute
  '/me/connections/new/subscription': typeof MeConnectionsNewSubscriptionRoute
  '/projects/$projectId/connections/$connectionId': typeof ProjectsProjectIdConnectionsConnectionIdRoute
  '/projects/$projectId/model-access/new': typeof ProjectsProjectIdModelAccessNewRoute
  '/projects/$projectId/model-access/subscription': typeof ProjectsProjectIdModelAccessSubscriptionRoute
  '/projects/$projectId/recipes/new': typeof ProjectsProjectIdRecipesNewRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
  '/admin/recipes/$recipeId/': typeof AdminRecipesRecipeIdIndexRoute
  '/projects/$projectId/connections/': typeof ProjectsProjectIdConnectionsIndexRoute
  '/projects/$projectId/recipes/': typeof ProjectsProjectIdRecipesIndexRoute
  '/admin/recipes/$recipeId/versions/new': typeof AdminRecipesRecipeIdVersionsNewRoute
  '/projects/$projectId/connections/new/api-key': typeof ProjectsProjectIdConnectionsNewApiKeyRoute
  '/projects/$projectId/connections/new/git': typeof ProjectsProjectIdConnectionsNewGitRoute
  '/projects/$projectId/recipes/$recipeId/': typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  '/projects/$projectId/recipes/$recipeId/versions/new': typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/setup/$token'
    | '/admin/'
    | '/admin/connections/$connectionId'
    | '/admin/connections/github-app'
    | '/admin/extensions/$extensionId'
    | '/admin/extensions/new'
    | '/admin/recipes/new'
    | '/admin/users/new'
    | '/me/connections/$connectionId'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/connections/'
    | '/admin/extensions/'
    | '/admin/recipes/'
    | '/admin/users/'
    | '/me/connections/'
    | '/admin/connections/new/api-key'
    | '/admin/connections/new/git'
    | '/me/connections/new/api-key'
    | '/me/connections/new/subscription'
    | '/projects/$projectId/connections/$connectionId'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId/'
    | '/projects/$projectId/connections/'
    | '/projects/$projectId/recipes/'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/connections/new/api-key'
    | '/projects/$projectId/connections/new/git'
    | '/projects/$projectId/recipes/$recipeId/'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/setup/$token'
    | '/admin'
    | '/admin/connections/$connectionId'
    | '/admin/connections/github-app'
    | '/admin/extensions/$extensionId'
    | '/admin/extensions/new'
    | '/admin/recipes/new'
    | '/admin/users/new'
    | '/me/connections/$connectionId'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/connections'
    | '/admin/extensions'
    | '/admin/recipes'
    | '/admin/users'
    | '/me/connections'
    | '/admin/connections/new/api-key'
    | '/admin/connections/new/git'
    | '/me/connections/new/api-key'
    | '/me/connections/new/subscription'
    | '/projects/$projectId/connections/$connectionId'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId'
    | '/projects/$projectId/connections'
    | '/projects/$projectId/recipes'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/connections/new/api-key'
    | '/projects/$projectId/connections/new/git'
    | '/projects/$projectId/recipes/$recipeId'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/tools'
    | '/admin/audit'
    | '/projects/$projectId'
    | '/projects/new'
    | '/setup/$token'
    | '/admin/'
    | '/admin/connections/$connectionId'
    | '/admin/connections/github-app'
    | '/admin/extensions/$extensionId'
    | '/admin/extensions/new'
    | '/admin/recipes/new'
    | '/admin/users/new'
    | '/me/connections/$connectionId'
    | '/projects/$projectId/model-access'
    | '/projects/$projectId/source'
    | '/projects/$projectId/verification'
    | '/admin/connections/'
    | '/admin/extensions/'
    | '/admin/recipes/'
    | '/admin/users/'
    | '/me/connections/'
    | '/admin/connections/new/api-key'
    | '/admin/connections/new/git'
    | '/me/connections/new/api-key'
    | '/me/connections/new/subscription'
    | '/projects/$projectId/connections/$connectionId'
    | '/projects/$projectId/model-access/new'
    | '/projects/$projectId/model-access/subscription'
    | '/projects/$projectId/recipes/new'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
    | '/admin/recipes/$recipeId/'
    | '/projects/$projectId/connections/'
    | '/projects/$projectId/recipes/'
    | '/admin/recipes/$recipeId/versions/new'
    | '/projects/$projectId/connections/new/api-key'
    | '/projects/$projectId/connections/new/git'
    | '/projects/$projectId/recipes/$recipeId/'
    | '/projects/$projectId/recipes/$recipeId/versions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ToolsRoute: typeof ToolsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  SetupTokenRoute: typeof SetupTokenRoute
  MeConnectionsConnectionIdRoute: typeof MeConnectionsConnectionIdRoute
  MeConnectionsIndexRoute: typeof MeConnectionsIndexRoute
  MeConnectionsNewApiKeyRoute: typeof MeConnectionsNewApiKeyRoute
  MeConnectionsNewSubscriptionRoute: typeof MeConnectionsNewSubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$token': {
      id: '/setup/$token'
      path: '/setup/$token'
      fullPath: '/setup/$token'
      preLoaderRoute: typeof SetupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connections/': {
      id: '/admin/connections/'
      path: '/connections'
      fullPath: '/admin/connections/'
      preLoaderRoute: typeof AdminConnectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connections/$connectionId': {
      id: '/admin/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/admin/connections/$connectionId'
      preLoaderRoute: typeof AdminConnectionsConnectionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connections/github-app': {
      id: '/admin/connections/github-app'
      path: '/connections/github-app'
      fullPath: '/admin/connections/github-app'
      preLoaderRoute: typeof AdminConnectionsGithubAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extensions/': {
      id: '/admin/extensions/'
      path: '/extensions'
      fullPath: '/admin/extensions/'
      preLoaderRoute: typeof AdminExtensionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extensions/$extensionId': {
      id: '/admin/extensions/$extensionId'
      path: '/extensions/$extensionId'
      fullPath: '/admin/extensions/$extensionId'
      preLoaderRoute: typeof AdminExtensionsExtensionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extensions/new': {
      id: '/admin/extensions/new'
      path: '/extensions/new'
      fullPath: '/admin/extensions/new'
      preLoaderRoute: typeof AdminExtensionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/': {
      id: '/admin/recipes/'
      path: '/recipes'
      fullPath: '/admin/recipes/'
      preLoaderRoute: typeof AdminRecipesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/recipes/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/me/connections/': {
      id: '/me/connections/'
      path: '/me/connections'
      fullPath: '/me/connections/'
      preLoaderRoute: typeof MeConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/connections/$connectionId': {
      id: '/me/connections/$connectionId'
      path: '/me/connections/$connectionId'
      fullPath: '/me/connections/$connectionId'
      preLoaderRoute: typeof MeConnectionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/model-access': {
      id: '/projects/$projectId/model-access'
      path: '/model-access'
      fullPath: '/projects/$projectId/model-access'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/source': {
      id: '/projects/$projectId/source'
      path: '/source'
      fullPath: '/projects/$projectId/source'
      preLoaderRoute: typeof ProjectsProjectIdSourceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/verification': {
      id: '/projects/$projectId/verification'
      path: '/verification'
      fullPath: '/projects/$projectId/verification'
      preLoaderRoute: typeof ProjectsProjectIdVerificationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/admin/connections/new/api-key': {
      id: '/admin/connections/new/api-key'
      path: '/connections/new/api-key'
      fullPath: '/admin/connections/new/api-key'
      preLoaderRoute: typeof AdminConnectionsNewApiKeyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connections/new/git': {
      id: '/admin/connections/new/git'
      path: '/connections/new/git'
      fullPath: '/admin/connections/new/git'
      preLoaderRoute: typeof AdminConnectionsNewGitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/$recipeId/': {
      id: '/admin/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/admin/recipes/$recipeId/'
      preLoaderRoute: typeof AdminRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/me/connections/new/api-key': {
      id: '/me/connections/new/api-key'
      path: '/me/connections/new/api-key'
      fullPath: '/me/connections/new/api-key'
      preLoaderRoute: typeof MeConnectionsNewApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/connections/new/subscription': {
      id: '/me/connections/new/subscription'
      path: '/me/connections/new/subscription'
      fullPath: '/me/connections/new/subscription'
      preLoaderRoute: typeof MeConnectionsNewSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/connections/': {
      id: '/projects/$projectId/connections/'
      path: '/connections'
      fullPath: '/projects/$projectId/connections/'
      preLoaderRoute: typeof ProjectsProjectIdConnectionsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/connections/$connectionId': {
      id: '/projects/$projectId/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/projects/$projectId/connections/$connectionId'
      preLoaderRoute: typeof ProjectsProjectIdConnectionsConnectionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/model-access/new': {
      id: '/projects/$projectId/model-access/new'
      path: '/new'
      fullPath: '/projects/$projectId/model-access/new'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessNewRouteImport
      parentRoute: typeof ProjectsProjectIdModelAccessRoute
    }
    '/projects/$projectId/model-access/subscription': {
      id: '/projects/$projectId/model-access/subscription'
      path: '/subscription'
      fullPath: '/projects/$projectId/model-access/subscription'
      preLoaderRoute: typeof ProjectsProjectIdModelAccessSubscriptionRouteImport
      parentRoute: typeof ProjectsProjectIdModelAccessRoute
    }
    '/projects/$projectId/recipes/': {
      id: '/projects/$projectId/recipes/'
      path: '/recipes'
      fullPath: '/projects/$projectId/recipes/'
      preLoaderRoute: typeof ProjectsProjectIdRecipesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/recipes/new': {
      id: '/projects/$projectId/recipes/new'
      path: '/recipes/new'
      fullPath: '/projects/$projectId/recipes/new'
      preLoaderRoute: typeof ProjectsProjectIdRecipesNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/new': {
      id: '/projects/$projectId/runs/new'
      path: '/runs/new'
      fullPath: '/projects/$projectId/runs/new'
      preLoaderRoute: typeof ProjectsProjectIdRunsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/admin/recipes/$recipeId/versions/new': {
      id: '/admin/recipes/$recipeId/versions/new'
      path: '/recipes/$recipeId/versions/new'
      fullPath: '/admin/recipes/$recipeId/versions/new'
      preLoaderRoute: typeof AdminRecipesRecipeIdVersionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId/connections/new/api-key': {
      id: '/projects/$projectId/connections/new/api-key'
      path: '/connections/new/api-key'
      fullPath: '/projects/$projectId/connections/new/api-key'
      preLoaderRoute: typeof ProjectsProjectIdConnectionsNewApiKeyRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/connections/new/git': {
      id: '/projects/$projectId/connections/new/git'
      path: '/connections/new/git'
      fullPath: '/projects/$projectId/connections/new/git'
      preLoaderRoute: typeof ProjectsProjectIdConnectionsNewGitRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/recipes/$recipeId/': {
      id: '/projects/$projectId/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/projects/$projectId/recipes/$recipeId/'
      preLoaderRoute: typeof ProjectsProjectIdRecipesRecipeIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/recipes/$recipeId/versions/new': {
      id: '/projects/$projectId/recipes/$recipeId/versions/new'
      path: '/recipes/$recipeId/versions/new'
      fullPath: '/projects/$projectId/recipes/$recipeId/versions/new'
      preLoaderRoute: typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConnectionsConnectionIdRoute: typeof AdminConnectionsConnectionIdRoute
  AdminConnectionsGithubAppRoute: typeof AdminConnectionsGithubAppRoute
  AdminExtensionsExtensionIdRoute: typeof AdminExtensionsExtensionIdRoute
  AdminExtensionsNewRoute: typeof AdminExtensionsNewRoute
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminConnectionsIndexRoute: typeof AdminConnectionsIndexRoute
  AdminExtensionsIndexRoute: typeof AdminExtensionsIndexRoute
  AdminRecipesIndexRoute: typeof AdminRecipesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminConnectionsNewApiKeyRoute: typeof AdminConnectionsNewApiKeyRoute
  AdminConnectionsNewGitRoute: typeof AdminConnectionsNewGitRoute
  AdminRecipesRecipeIdIndexRoute: typeof AdminRecipesRecipeIdIndexRoute
  AdminRecipesRecipeIdVersionsNewRoute: typeof AdminRecipesRecipeIdVersionsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConnectionsConnectionIdRoute: AdminConnectionsConnectionIdRoute,
  AdminConnectionsGithubAppRoute: AdminConnectionsGithubAppRoute,
  AdminExtensionsExtensionIdRoute: AdminExtensionsExtensionIdRoute,
  AdminExtensionsNewRoute: AdminExtensionsNewRoute,
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminConnectionsIndexRoute: AdminConnectionsIndexRoute,
  AdminExtensionsIndexRoute: AdminExtensionsIndexRoute,
  AdminRecipesIndexRoute: AdminRecipesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminConnectionsNewApiKeyRoute: AdminConnectionsNewApiKeyRoute,
  AdminConnectionsNewGitRoute: AdminConnectionsNewGitRoute,
  AdminRecipesRecipeIdIndexRoute: AdminRecipesRecipeIdIndexRoute,
  AdminRecipesRecipeIdVersionsNewRoute: AdminRecipesRecipeIdVersionsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsProjectIdModelAccessRouteChildren {
  ProjectsProjectIdModelAccessNewRoute: typeof ProjectsProjectIdModelAccessNewRoute
  ProjectsProjectIdModelAccessSubscriptionRoute: typeof ProjectsProjectIdModelAccessSubscriptionRoute
}

const ProjectsProjectIdModelAccessRouteChildren: ProjectsProjectIdModelAccessRouteChildren =
  {
    ProjectsProjectIdModelAccessNewRoute: ProjectsProjectIdModelAccessNewRoute,
    ProjectsProjectIdModelAccessSubscriptionRoute:
      ProjectsProjectIdModelAccessSubscriptionRoute,
  }

const ProjectsProjectIdModelAccessRouteWithChildren =
  ProjectsProjectIdModelAccessRoute._addFileChildren(
    ProjectsProjectIdModelAccessRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdModelAccessRoute: typeof ProjectsProjectIdModelAccessRouteWithChildren
  ProjectsProjectIdSourceRoute: typeof ProjectsProjectIdSourceRoute
  ProjectsProjectIdVerificationRoute: typeof ProjectsProjectIdVerificationRoute
  ProjectsProjectIdConnectionsConnectionIdRoute: typeof ProjectsProjectIdConnectionsConnectionIdRoute
  ProjectsProjectIdRecipesNewRoute: typeof ProjectsProjectIdRecipesNewRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
  ProjectsProjectIdRunsNewRoute: typeof ProjectsProjectIdRunsNewRoute
  ProjectsProjectIdConnectionsIndexRoute: typeof ProjectsProjectIdConnectionsIndexRoute
  ProjectsProjectIdRecipesIndexRoute: typeof ProjectsProjectIdRecipesIndexRoute
  ProjectsProjectIdConnectionsNewApiKeyRoute: typeof ProjectsProjectIdConnectionsNewApiKeyRoute
  ProjectsProjectIdConnectionsNewGitRoute: typeof ProjectsProjectIdConnectionsNewGitRoute
  ProjectsProjectIdRecipesRecipeIdIndexRoute: typeof ProjectsProjectIdRecipesRecipeIdIndexRoute
  ProjectsProjectIdRecipesRecipeIdVersionsNewRoute: typeof ProjectsProjectIdRecipesRecipeIdVersionsNewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdModelAccessRoute:
    ProjectsProjectIdModelAccessRouteWithChildren,
  ProjectsProjectIdSourceRoute: ProjectsProjectIdSourceRoute,
  ProjectsProjectIdVerificationRoute: ProjectsProjectIdVerificationRoute,
  ProjectsProjectIdConnectionsConnectionIdRoute:
    ProjectsProjectIdConnectionsConnectionIdRoute,
  ProjectsProjectIdRecipesNewRoute: ProjectsProjectIdRecipesNewRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
  ProjectsProjectIdRunsNewRoute: ProjectsProjectIdRunsNewRoute,
  ProjectsProjectIdConnectionsIndexRoute:
    ProjectsProjectIdConnectionsIndexRoute,
  ProjectsProjectIdRecipesIndexRoute: ProjectsProjectIdRecipesIndexRoute,
  ProjectsProjectIdConnectionsNewApiKeyRoute:
    ProjectsProjectIdConnectionsNewApiKeyRoute,
  ProjectsProjectIdConnectionsNewGitRoute:
    ProjectsProjectIdConnectionsNewGitRoute,
  ProjectsProjectIdRecipesRecipeIdIndexRoute:
    ProjectsProjectIdRecipesRecipeIdIndexRoute,
  ProjectsProjectIdRecipesRecipeIdVersionsNewRoute:
    ProjectsProjectIdRecipesRecipeIdVersionsNewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ToolsRoute: ToolsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  SetupTokenRoute: SetupTokenRoute,
  MeConnectionsConnectionIdRoute: MeConnectionsConnectionIdRoute,
  MeConnectionsIndexRoute: MeConnectionsIndexRoute,
  MeConnectionsNewApiKeyRoute: MeConnectionsNewApiKeyRoute,
  MeConnectionsNewSubscriptionRoute: MeConnectionsNewSubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
