// Real browser -> real HTTPS application -> isolated PostgreSQL. No API mocks.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chromium, request, expect } from "@playwright/test";

const origin = process.env.BLAXSMITH_E2E_ORIGIN;
assert.ok(origin?.startsWith("https://127.0.0.1:"), "run through the disposable Go E2E harness");
const browser = await chromium.launch({ channel: process.env.BLAXSMITH_E2E_BROWSER_CHANNEL || "chrome" });
const context = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 1000 } });
context.setDefaultTimeout(10_000);
const page = await context.newPage();
const pageErrors = []; page.on("pageerror", (error) => pageErrors.push(error.message));
const api = (service, method, data, headers = {}) => context.request.post(`${origin}/api/blaxsmith.api.v1.${service}/${method}`, { data, headers: { Origin: origin, ...headers } });
try {
 const csrf = await (await api("AuthService", "GetCsrf", {})).json();
 const login = await api("AuthService", "LoginLocal", { organizationSlug: "engineering", email: "alice@example.com", password: "correct horse battery staple" }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(login.status(), 200);
 const created = await api("WorkflowService", "CreateProject", { slug: "browser-e2e", name: "Browser E2E" }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(created.status(), 200); const { project } = await created.json();
 const catalogGrant = await api("ConnectionService", "GrantConnection", { connectionId: "e2e-advice-connection", projectId: project.id, granteeKind: "project" }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(catalogGrant.status(), 200);
 for (const model of ["gpt-6-luna", "gpt-6-sol", "gpt-6-astra"]) {
  const use = await api("ConnectionService", "AddConnectionUse", { connectionId: "e2e-advice-connection", projectId: project.id, model }, { "X-Blaxsmith-CSRF": csrf.token });
  assert.equal(use.status(), 200);
 }
 console.log("E2E: policy presets and concurrent revisions");
 const checkBody = { projectId: project.id, checks: [{ id: "build", category: "build", mode: "required", command: ["go", "build", "./..."] }, { id: "browser", category: "e2e", mode: "advisory", command: ["npm", "run", "e2e"] }], preset: "balanced" };
 const initialPolicy = await api("WorkflowService", "SetProjectVerification", checkBody, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(initialPolicy.status(), 200);
 const policyURL = `${origin}/projects/${project.id}/settings/verification`;
 await page.goto(policyURL);
 await page.getByRole("combobox", { name: "Check preset", exact: true }).selectOption("mvp");
 await expect(page.getByRole("combobox", { name: "Enforcement", exact: true }).nth(1)).toHaveValue("off");
 await page.getByRole("button", { name: "Save checks", exact: true }).click();
 await expect(page.getByText(/Version 2 · updated/)).toBeVisible();
 // A second writer updates the live revision while this editor keeps its draft.
 await page.getByRole("combobox", { name: "Enforcement", exact: true }).nth(1).selectOption("advisory");
 await expect(page.getByRole("combobox", { name: "Check preset", exact: true })).toHaveValue("custom");
 const otherSave = await api("WorkflowService", "SetProjectVerification", { ...checkBody, expectedVersion: "2", preset: "thorough", checks: checkBody.checks.map((check) => ({ ...check, mode: "required" })) }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(otherSave.status(), 200);
 await page.getByRole("button", { name: "Save checks", exact: true }).click();
 await expect(page.getByText(/Checks changed elsewhere/)).toBeVisible();
 await expect(page.getByRole("combobox", { name: "Enforcement", exact: true }).nth(1)).toHaveValue("advisory");
 await page.getByRole("button", { name: "Cancel", exact: true }).click();
 await expect(page.getByRole("combobox", { name: "Check preset", exact: true })).toHaveValue("thorough");
 await expect(page.getByRole("combobox", { name: "Enforcement", exact: true }).nth(1)).toHaveValue("required");
 await page.getByText("Check policy history", { exact: true }).click();
 await expect(page.getByRole("heading", { name: "Version 2 · mvp", exact: true })).toBeVisible();
 const history = await (await api("WorkflowService", "ListProjectVerificationHistory", { projectId: project.id })).json();
 assert.deepEqual(history.revisions.map((v) => v.version), ["3", "2", "1"]);
 assert.deepEqual(history.revisions.map((v) => v.checks[1].mode), ["required", "off", "advisory"]);
 const badPreset = await api("WorkflowService", "SetProjectVerification", { ...checkBody, expectedVersion: "3", preset: "thorough" }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(badPreset.status(), 400, "a preset must match the actual selected modes");
 const currentPolicy = await (await api("WorkflowService", "GetProjectVerification", { projectId: project.id })).json();
 assert.equal(currentPolicy.verification.version, "3");
 console.log("E2E: open goals");
 await page.goto(`${origin}/projects/${project.id}/goals`);
 await page.getByRole("textbox", { name: "Goal title", exact: true }).fill("Preserve saved settings");
 await page.getByRole("textbox", { name: "What do you want to accomplish?", exact: true }).fill("Keep settings after reload and preserve prior values on invalid input.");
 await page.getByRole("button", { name: "Start conversation", exact: true }).click();
 await expect(page.getByRole("heading", { name: "Preserve saved settings", exact: true })).toBeVisible();
 await page.getByText("Reported usage", { exact: true }).click();
 await expect(page.getByText("No harness usage reports collected. Token usage and cost are unknown, not zero.", { exact: true })).toBeVisible();
 console.log("E2E: goal created");
 const goalURL = page.url();
 console.log("E2E: durable goal pause and resume");
 await page.getByRole("button", { name: "Pause new work", exact: true }).click();
 await expect(page.getByRole("heading", { name: "Goal admission · paused", exact: true })).toBeVisible();
 await page.reload();
 await expect(page.getByRole("heading", { name: "Goal admission · paused", exact: true })).toBeVisible();
 await page.getByRole("button", { name: "Resume goal", exact: true }).click();
 await expect(page.getByRole("heading", { name: "Goal admission · active", exact: true })).toBeVisible();
 await page.getByText("Goal execution allowance", { exact: true }).click();
 await page.getByRole("button", { name: "Edit allowance", exact: true }).click();
 await page.getByRole("spinbutton", { name: "Maximum goal runs", exact: true }).fill("4");
 await page.getByRole("spinbutton", { name: "Maximum goal attempts", exact: true }).fill("12");
 await page.getByRole("spinbutton", { name: "Repeated required-check failure limit", exact: true }).fill("3");
 await page.getByRole("spinbutton", { name: "No-progress limit (seconds)", exact: true }).fill("900");
 await page.getByRole("checkbox", { name: "Start a new stall recovery window", exact: true }).check();
 await page.setViewportSize({ width: 390, height: 844 });
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "stall controls overflow mobile");
 await page.getByRole("group", { name: "Admission limits", exact: true }).screenshot({ path: "/tmp/blaxsmith-stall-controls-e2e.png" });
 await page.setViewportSize({ width: 1440, height: 1000 });
 await page.getByRole("button", { name: "Save allowance", exact: true }).click();
 await expect(page.getByText(/Allowance version 1 · updated/)).toBeVisible();
 await expect(page.getByText(/Repeated required-check failures: 0 \/ 3. Progress window: 900 seconds/)).toBeVisible();
 const stallLimits = await (await api("WorkflowService", "GetGoalAllowance", { goalId: new URL(goalURL).pathname.split("/").at(-1) })).json();
 assert.equal(stallLimits.allowance.maxRepeatedCheckFailures, 3); assert.equal(stallLimits.allowance.noProgressSeconds, 900); assert.ok(stallLimits.allowance.stallResetAt);
 assert.ok(!stallLimits.allowance.admissionClosed, "no-progress timer waits for the first admitted run");
 await page.getByRole("button", { name: "Edit allowance", exact: true }).click();
 const allowanceChanged = await api("WorkflowService", "SetGoalAllowance", { goalId: new URL(goalURL).pathname.split("/").at(-1), expectedVersion: "1", maxRuns: 3, maxAttempts: 10 }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(allowanceChanged.status(), 200);
 await page.getByRole("spinbutton", { name: "Maximum goal attempts", exact: true }).fill("20");
 await page.getByRole("button", { name: "Save allowance", exact: true }).click();
 await expect(page.getByRole("alert").filter({ hasText: "goal allowance changed" })).toBeVisible();
 await expect(page.getByRole("spinbutton", { name: "Maximum goal attempts", exact: true })).toHaveValue("20");
 await page.getByRole("button", { name: "Cancel allowance edit", exact: true }).click();
 await page.getByText("Goal execution allowance", { exact: true }).click();
 await page.getByRole("textbox", { name: "Add context", exact: true }).fill("Use the existing service and tests.");
 await page.getByRole("button", { name: "Save message", exact: true }).click();
 await expect(page.getByRole("textbox", { name: "Add context", exact: true })).toHaveValue("");
 const plan = { schema_version: "anvil.plan/v1alpha1", title: "Saved settings", summary: "Preserve existing behavior", assumptions: [], out_of_scope: [], open_questions: [], requirements: [{ id: "R1", description: "Retain settings", sources: ["brief"], examples: ["Reload restores settings"] }], phases: [{ id: "P1", title: "Deliver", outcome: "Working settings" }], tasks: [{ id: "T1", title: "Implement settings", phase: "P1", reason: "Preserve behavior", instructions: "Inspect callers", depends_on: [], requirement_ids: ["R1"], acceptance: ["Settings survive reload"], validation: ["Service tests"] }] };
 console.log("E2E: import plan");
 await page.getByRole("button", { name: "Import plan JSON", exact: true }).click();
 await page.getByRole("textbox", { name: "Anvil plan JSON", exact: true }).fill(JSON.stringify(plan));
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByText("Plan version 1 saved.", { exact: true })).toBeVisible();
 const invalidDecision = structuredClone(plan);
 invalidDecision.decisions = [{ id: "D1", question: "Use a new service?", choice: "Yes", reason: "Unsupported attribution", authority: "user", sources: ["question:never-answered"] }];
 const goalID = new URL(goalURL).pathname.split("/").at(-1);
 const goalState = await (await api("WorkflowService", "GetGoal", { goalId: goalID })).json();
 const rejectedDecision = await api("WorkflowService", "SaveGoalPlan", { goalId: goalID, expectedGoalRevision: goalState.goal.revision, expectedPlanVersion: "1", requestKey: "invalid-decision", contentJson: JSON.stringify(invalidDecision) }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(rejectedDecision.status(), 400);
 await page.getByRole("button", { name: "Edit plan", exact: true }).click();
 await page.locator(".plan-editor summary").filter({ hasText: "T1" }).click();
 await page.getByRole("textbox", { name: "T1 instructions", exact: true }).fill("Read callers and preserve existing errors.");
 await page.getByRole("textbox", { name: "T1 acceptance criteria 1", exact: true }).fill("Reload restores settings\nInvalid input preserves the previous value");
 await page.getByText("Edit decisions and classified unknowns", { exact: true }).click();
 await page.getByRole("button", { name: "Add decision", exact: true }).click();
 await page.getByRole("textbox", { name: "D1 question", exact: true }).fill("Which persistence layer?");
 await page.getByRole("textbox", { name: "D1 choice", exact: true }).fill("Reuse the existing service");
 await page.getByRole("textbox", { name: "D1 reason", exact: true }).fill("Preserve established behavior");
 await page.getByRole("button", { name: "Add unknown", exact: true }).click();
 await page.getByRole("textbox", { name: "U1 description", exact: true }).fill("What is the browser test environment?");
 await page.getByRole("combobox", { name: "U1 classification", exact: true }).selectOption("blocking");
 await page.getByRole("textbox", { name: "U1 reason", exact: true }).fill("Need a reproducible endpoint");
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByText("Plan version 2 saved.", { exact: true })).toBeVisible();
 await expect(page.getByRole("heading", { name: "Planning readiness · 1 unresolved questions", exact: true })).toBeVisible();
 await page.getByText("Compare version 1 → 2", { exact: true }).click();
 await expect(page.getByText("Changed T1", { exact: true })).toBeVisible();
 await page.getByRole("button", { name: "Edit plan", exact: true }).click();
 await page.getByRole("button", { name: "Add phase", exact: true }).click();
 await page.getByRole("textbox", { name: "P2 phase title", exact: true }).fill("Validate delivery");
 await page.getByRole("textbox", { name: "P2 outcome", exact: true }).fill("Critical behavior demonstrated");
 await page.getByRole("button", { name: "Add task to P2", exact: true }).click();
 await page.locator(".plan-editor summary").filter({ hasText: "T2" }).click();
 await page.getByRole("textbox", { name: "T2 title", exact: true }).fill("Exercise reload journey");
 await page.getByRole("textbox", { name: "T2 reasoning", exact: true }).fill("Prove persistence at the user boundary");
 await page.getByRole("textbox", { name: "T2 instructions", exact: true }).fill("Use the real browser against the application and database.");
 await page.getByRole("textbox", { name: "T2 acceptance criteria 1", exact: true }).fill("Reload retains the saved value");
 await page.getByRole("group", { name: "T2 dependencies", exact: true }).getByRole("checkbox", { name: "T1 · Implement settings", exact: true }).check();
 await page.getByRole("group", { name: "T2 requirements", exact: true }).getByRole("checkbox", { name: "R1 · Retain settings", exact: true }).check();
 await page.locator(".plan-editor summary").filter({ hasText: "Edit requirements and examples" }).click();
 await page.getByRole("button", { name: "Add requirement", exact: true }).click();
 await page.getByRole("textbox", { name: "R2 description", exact: true }).fill("Reject invalid values");
 await page.getByRole("textbox", { name: "R2 examples 1", exact: true }).fill("An invalid value leaves saved settings unchanged");
 await page.getByRole("group", { name: "T2 requirements", exact: true }).getByRole("checkbox", { name: "R2 · Reject invalid values", exact: true }).check();
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByText("Plan version 3 saved.", { exact: true })).toBeVisible();
 await expect(page.getByText("Requirement coverage · 2/2 assigned", { exact: true })).toBeVisible();
 await page.getByText("Compare version 2 → 3", { exact: true }).click();
 await expect(page.getByText("Added T2", { exact: true })).toBeVisible();
 await expect(page.getByText("Added R2", { exact: true })).toBeVisible();
 await page.reload();
 await page.getByRole("button", { name: "Edit plan", exact: true }).click();
 await page.locator(".plan-editor summary").filter({ hasText: "T1" }).click();
 await expect(page.getByRole("textbox", { name: "T1 instructions", exact: true })).toHaveValue("Read callers and preserve existing errors.");
 await page.getByRole("textbox", { name: "T1 instructions", exact: true }).fill("");
 await page.locator(".plan-editor summary").filter({ hasText: "T1" }).click();
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByRole("textbox", { name: "T1 instructions", exact: true })).toBeFocused();
 await page.getByRole("textbox", { name: "T1 instructions", exact: true }).fill("Keep this unsaved draft.");
 const impact = page.locator("form .plan-impact");
 await impact.getByText("Change impact · 2 assignments need review", { exact: true }).click();
 await expect(impact.getByText("Task assignment changed", { exact: true })).toBeVisible();
 await expect(impact.getByText("Depends on affected T1", { exact: true })).toBeVisible();
 await page.getByRole("textbox", { name: "T1 instructions", exact: true }).fill("Read callers and preserve existing errors.");
 await expect(impact.getByText("Change impact · 0 assignments need review", { exact: true })).toBeVisible();
 await page.getByRole("textbox", { name: "T1 instructions", exact: true }).fill("Keep this unsaved draft.");
 await page.getByRole("textbox", { name: "Add context", exact: true }).fill("A new decision changes the goal revision.");
 await page.getByRole("button", { name: "Save message", exact: true }).click();
 await expect(page.getByRole("button", { name: "Save new version", exact: true })).toBeDisabled();
 await expect(page.getByRole("textbox", { name: "T1 instructions", exact: true })).toHaveValue("Keep this unsaved draft.");
 await page.getByRole("button", { name: "Cancel edit", exact: true }).click();
 await page.getByRole("button", { name: "Revise plan JSON", exact: true }).click();
 plan.tasks[0].depends_on = ["T1"];
 await page.getByRole("textbox", { name: "Anvil plan JSON", exact: true }).fill(JSON.stringify(plan));
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByRole("alert").filter({ hasText: "cycle" })).toBeVisible();
 await expect(page.getByRole("textbox", { name: "Anvil plan JSON", exact: true })).toHaveValue(JSON.stringify(plan));
 await page.getByRole("button", { name: "Cancel edit", exact: true }).click();
 await page.setViewportSize({ width: 390, height: 844 });
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "goal workspace overflows mobile");
 await page.getByRole("button", { name: "Revise plan JSON", exact: true }).click();
 await page.getByRole("button", { name: "Save new version", exact: true }).click();
 await expect(page.getByText("Plan version 4 saved.", { exact: true })).toBeVisible();
 await page.getByText("Prepare implementation", { exact: true }).click();
 await expect(page.getByRole("combobox", { name: "Starting code", exact: true })).toHaveValue("");
 await page.getByText("Model guidance for implementation", { exact: true }).click();
 await page.getByRole("combobox", { name: "Model preference", exact: true }).last().selectOption("preserve");
 await expect(page.getByText("Suggested capability: focused · effort: low", { exact: true })).toBeVisible();
 await expect(page.getByRole("textbox", { name: "Effort", exact: true }).last()).toHaveValue("medium");
 await page.getByRole("checkbox", { name: "High consequence errors", exact: true }).last().check();
 await expect(page.getByText("Suggested capability: deep · effort: high", { exact: true })).toBeVisible();
 await expect(page.getByRole("textbox", { name: "Effort", exact: true }).last()).toHaveValue("medium");
 await page.getByRole("button", { name: "Apply suggested model and effort", exact: true }).last().click();
 await expect(page.getByRole("combobox", { name: "Model", exact: true }).last()).toHaveValue("e2e-advice-connection:gpt-6-astra");
 await expect(page.getByRole("textbox", { name: "Effort", exact: true }).last()).toHaveValue("high");
 await expect(page.getByRole("textbox", { name: "Model account (connection ID)", exact: true }).last()).toHaveValue("e2e-advice-connection");
 await page.getByRole("checkbox", { name: "High consequence errors", exact: true }).last().uncheck();
 await page.getByRole("button", { name: "Apply suggested model and effort", exact: true }).last().click();
 await expect(page.getByRole("combobox", { name: "Model", exact: true }).last()).toHaveValue("e2e-advice-connection:gpt-6-luna");
 await expect(page.getByRole("textbox", { name: "Effort", exact: true }).last()).toHaveValue("low");
 await expect(page.getByRole("combobox", { name: "Independent code review", exact: true })).toHaveValue("off");
 await page.getByText("Model guidance for implementation", { exact: true }).click();
 await page.getByRole("combobox", { name: "Planning readiness", exact: true }).selectOption("required");
 await expect(page.getByRole("combobox", { name: "Planning readiness", exact: true })).toHaveValue("required");
 await page.getByRole("combobox", { name: "Planning readiness", exact: true }).selectOption("advisory");
 await page.getByText("Repository rules and skills · 0 selected", { exact: true }).last().click();
 await page.getByRole("textbox", { name: "Project inputs file", exact: true }).last().fill(".blaxsmith/inputs.json");
 await page.getByRole("textbox", { name: "Agent definition", exact: true }).last().fill("implementer");
 await expect(page.getByRole("textbox", { name: "Agent definition", exact: true }).last()).toHaveValue("implementer");
 await page.getByRole("textbox", { name: "Project inputs file", exact: true }).last().fill("");
 await expect(page.getByRole("textbox", { name: "Agent definition", exact: true }).last()).toHaveValue("");
 await expect(page.getByRole("textbox", { name: "Agent definition", exact: true }).last()).toBeDisabled();
 await page.getByRole("combobox", { name: "Independent code review", exact: true }).selectOption("required");
 await expect(page.getByRole("group", { name: "Independent reviewer", exact: true })).toBeVisible();
 await expect(page.getByRole("button", { name: "Preview implementation", exact: true })).toBeDisabled();
 await page.getByRole("combobox", { name: "Independent code review", exact: true }).selectOption("off");
 await expect(page.getByRole("group", { name: "Independent reviewer", exact: true })).toHaveCount(0);
 console.log("E2E: external factory isolation");
 const external = await api("WorkflowService", "CreateGoal", { projectId: project.id, requestKey: "external-factory", title: "External factory plan", brief: "Use a separate factory schema.", factoryId: "example-factory", factoryVersion: "1.2.3", questions: [{ id: "success", title: "External success condition", allowFreeText: true }] }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(external.status(), 200);
 const externalGoal = (await external.json()).goal;
 assert.equal(externalGoal.factoryId, "example-factory");
 assert.equal(externalGoal.questions.length, 1);
 const externalPlan = { schema_version: "example-factory/plan/v1", steps: [{ action: "inspect", details: "Factory-owned semantics" }], exact_integer: "9007199254740993" };
 const saveExternal = await api("WorkflowService", "SaveGoalPlan", { goalId: externalGoal.id, requestKey: "external-plan", expectedGoalRevision: "1", contentJson: JSON.stringify(externalPlan) }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(saveExternal.status(), 200);
 const wrongSchema = await api("WorkflowService", "SaveGoalPlan", { goalId: externalGoal.id, requestKey: "external-plan-wrong", expectedGoalRevision: "1", expectedPlanVersion: "1", contentJson: JSON.stringify(plan) }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(wrongSchema.status(), 400);
 const nativePlan = await api("WorkflowService", "StartGoalPlanning", { goalId: externalGoal.id, expectedRevision: "1", requestKey: "external-start" }, { "X-Blaxsmith-CSRF": csrf.token });
 assert.equal(nativePlan.status(), 400);
 assert.match((await nativePlan.json()).message, /external or unsupported factory/);
 await page.goto(`${origin}/projects/${project.id}/goals/${externalGoal.id}`);
 await expect(page.getByRole("heading", { name: "example-factory plan", exact: true })).toBeVisible();
 await expect(page.getByRole("button", { name: "Edit plan", exact: true })).toHaveCount(0);
 await expect(page.getByText("Start an Anvil planning run", { exact: true })).toHaveCount(0);
 await page.getByRole("button", { name: "Revise plan JSON", exact: true }).click();
 assert.deepEqual(JSON.parse(await page.getByRole("textbox", { name: "Factory plan JSON", exact: true }).inputValue()), externalPlan);
 await page.getByRole("button", { name: "Cancel edit", exact: true }).click();
 console.log("E2E: agent access");
 await page.goto(`${origin}/projects/${project.id}/settings/agents`);
 await page.getByRole("textbox", { name: "Credential label", exact: true }).fill("E2E external factory");
 await page.getByRole("checkbox", { name: "Create goals, answer starter questions and save plans" }).check();
 await page.getByRole("button", { name: "Create credential", exact: true }).click();
 const secret = await page.getByLabel("API token", { exact: true }).inputValue();
 assert.match(secret, /^bxs_/);
 const machine = await request.newContext({ ignoreHTTPSErrors: true, extraHTTPHeaders: { Authorization: `Bearer ${secret}` } });
 try {
  const endpoint = `${origin}/machine/blaxsmith.api.v1.WorkflowService/`;
  const got = await machine.post(endpoint + "GetGoal", { data: { goalId: goalURL.split("/").at(-1) } });
  assert.equal(got.status(), 200);
  const denied = await machine.post(endpoint + "GetProject", { data: { projectId: "00000000-0000-0000-0000-000000000000" } });
  assert.equal(denied.status(), 403);
  await page.reload();
  await expect(page.getByLabel("API token", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Revoke E2E external factory", exact: true }).click();
  await expect(page.getByText("Revoked", { exact: true })).toBeVisible();
  const revoked = await machine.post(endpoint + "GetGoal", { data: { goalId: goalURL.split("/").at(-1) } });
  assert.equal(revoked.status(), 401);
 } finally { await machine.dispose(); }
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "agent settings overflow mobile");
 console.log("E2E: service identity management");
 await page.getByText("Add service identity", { exact: true }).click();
 await page.getByRole("textbox", { name: "Service identity name", exact: true }).fill("Browser factory service");
 await page.getByRole("button", { name: "Create service identity", exact: true }).click();
 await expect(page.getByRole("combobox", { name: "Act as", exact: true })).not.toHaveValue("");
 await expect(page.getByRole("checkbox", { name: "Accept current review packages or request corrections" })).toHaveCount(0);
 await page.getByRole("textbox", { name: "Credential label", exact: true }).fill("Service browser credential");
 await page.getByRole("button", { name: "Create credential", exact: true }).click();
 await expect(page.getByLabel("API token", { exact: true })).toHaveValue(/^bxs_/);
 await page.getByRole("button", { name: "Dismiss token", exact: true }).click();
 await page.getByText("Disable service identity…", { exact: true }).click();
 await page.getByRole("button", { name: "Disable selected service identity", exact: true }).click();
 await expect(page.getByRole("button", { name: "Create credential", exact: true })).toBeDisabled();
 await expect(page.getByRole("button", { name: "Revoke Service browser credential", exact: true })).toBeDisabled();
 console.log("E2E: historical checkpoint");
 await page.goto(`${origin}/projects/${process.env.BLAXSMITH_E2E_REPORT_PROJECT}/goals/${process.env.BLAXSMITH_E2E_CHECKPOINT_GOAL}`);
 await expect(page.getByRole("heading", { name: "Accepted checkpoints", exact: true })).toBeVisible();
 await expect(page.getByText("Plan 1 · goal context 2 · Historical acceptance · superseded", { exact: true })).toBeVisible();
 await page.getByText("Record an accepted checkpoint", { exact: true }).click();
 await page.getByRole("combobox", { name: "Checkpoint run", exact: true }).selectOption(process.env.BLAXSMITH_E2E_REPORT_RUN);
 await page.getByRole("textbox", { name: "Checkpoint title", exact: true }).fill("Cannot certify rejected work");
 await expect(page.getByText("This run has no current accepted package. Inspect its review before recording a checkpoint.", { exact: true })).toBeVisible();
 await expect(page.getByRole("button", { name: "Record checkpoint", exact: true })).toBeDisabled();
 await page.reload();
 await expect(page.getByText("Plan 1 · goal context 2 · Historical acceptance · superseded", { exact: true })).toBeVisible();
 console.log("E2E: usage and delivery export");
 await page.goto(`${origin}/projects/${process.env.BLAXSMITH_E2E_REPORT_PROJECT}/runs/${process.env.BLAXSMITH_E2E_REPORT_RUN}`);
 await page.getByText("Reported usage", { exact: true }).click();
 await expect(page.getByText("1 of 3 attempts have reports. Coverage does not establish complete measurement.", { exact: true })).toBeVisible();
 await expect(page.getByText("Reported input tokens (including cache)", { exact: true })).toBeVisible();
 await expect(page.getByText("300", { exact: true })).toBeVisible();
 await expect(page.getByText("Unknown", { exact: true })).toBeVisible();
 await page.goto(`${origin}/projects/${process.env.BLAXSMITH_E2E_REPORT_PROJECT}/runs/${process.env.BLAXSMITH_E2E_REPORT_RUN}?tab=review`);
 await page.getByRole("button", { name: "Prepare delivery export", exact: true }).click();
 const downloadReady = page.waitForEvent("download");
 await page.getByRole("link", { name: "Download delivery snapshot (.md)", exact: true }).click();
 const download = await downloadReady;
 const stream = await download.createReadStream(); const chunks = []; for await (const chunk of stream) chunks.push(chunk);
 const markdown = Buffer.concat(chunks).toString("utf8");
 assert.match(markdown, /# Blaxsmith delivery snapshot/);
 assert.match(markdown, /Changes requested/);
 assert.match(markdown, /300 input tokens/);
 assert.match(markdown, /Merge \/ deployment: not established/);
 const reportHash = createHash("sha256").update(markdown).digest("hex");
 assert.ok(download.suggestedFilename().includes(reportHash.slice(0,12)));
 await page.getByText("Preview export", { exact: true }).click();
 await expect(page.getByRole("textbox", { name: "Delivery Markdown", exact: true })).toHaveValue(markdown);
 console.log("E2E: MCP OAuth browser consent");
 const verifier = "b".repeat(43);
 const authorization = new URLSearchParams({ response_type: "code", client_id: "test-mcp", redirect_uri: "https://client.example.test/callback", resource: `${origin}/mcp`, scope: "project.read goal.write", state: "browser-oauth", code_challenge_method: "S256", code_challenge: createHash("sha256").update(verifier).digest("base64url") });
 await page.route("https://client.example.test/callback**", (route) => route.fulfill({ status: 200, contentType: "text/html", body: "<h1>Client callback received</h1>" }));
 await page.goto(`${origin}/oauth/authorize?${authorization}`);
 await expect(page.getByRole("heading", { name: "Authorize an MCP client" })).toBeVisible();
 await expect(page.getByRole("checkbox", { name: "Create and edit goals, plans and accepted checkpoints" })).not.toBeChecked();
 await expect(page.getByRole("button", { name: "Authorize client", exact: true })).toBeDisabled();
 await page.getByRole("button", { name: "Deny access", exact: true }).click();
 await expect(page.getByRole("heading", { name: "Client callback received" })).toBeVisible();
 let callback = new URL(page.url());
 assert.equal(callback.searchParams.get("error"), "access_denied");
 assert.equal(callback.searchParams.get("code"), null);
 assert.equal(callback.searchParams.get("iss"), origin);
 await page.goto(`${origin}/oauth/authorize?${authorization}`);
 await page.getByRole("combobox", { name: "Project to authorize" }).selectOption(process.env.BLAXSMITH_E2E_REPORT_PROJECT);
 await page.getByRole("checkbox", { name: "Create and edit goals, plans and accepted checkpoints" }).check();
 await page.screenshot({ path: "/tmp/blaxsmith-mcp-consent-e2e.png", fullPage: true });
 await page.getByRole("button", { name: "Authorize client", exact: true }).click();
 await expect(page.getByRole("heading", { name: "Client callback received" })).toBeVisible();
 callback = new URL(page.url());
 assert.equal(callback.searchParams.get("state"), "browser-oauth");
 assert.equal(callback.searchParams.get("iss"), origin);
 assert.ok(callback.searchParams.get("code"));
 const oauthClient = await request.newContext({ ignoreHTTPSErrors: true });
 try {
  const issued = await oauthClient.post(`${origin}/oauth/token`, { form: { grant_type: "authorization_code", client_id: "test-mcp", code: callback.searchParams.get("code"), code_verifier: verifier, resource: `${origin}/mcp` } });
  assert.equal(issued.status(), 200);
  const token = await issued.json();
  assert.equal(token.scope, "goal.write project.read");
  const crossed = await oauthClient.post(`${origin}/machine/blaxsmith.api.v1.WorkflowService/DescribeMachineAccess`, { data: {}, headers: { Authorization: `Bearer ${token.access_token}` } });
  assert.equal(crossed.status(), 401);
  await page.goto(`${origin}/projects/${process.env.BLAXSMITH_E2E_REPORT_PROJECT}/settings/agents`);
  const credential = page.locator(".agent-credentials li").filter({ hasText: "MCP: E2E MCP" }).filter({ has: page.getByRole("button", { name: "Revoke MCP: E2E MCP", exact: true }).and(page.locator(":enabled")) });
  await expect(credential.getByText(`MCP only: ${origin}/mcp`, { exact: true })).toBeVisible();
  const revokeFinished = page.waitForResponse((response) => response.url().endsWith("/RevokeApiToken") && response.status() === 200);
  await credential.getByRole("button", { name: "Revoke MCP: E2E MCP", exact: true }).click();
  await revokeFinished;
  const revoked = await oauthClient.post(`${origin}/mcp`, { data: {}, headers: { Authorization: `Bearer ${token.access_token}` } });
  assert.equal(revoked.status(), 401);
 } finally { await oauthClient.dispose(); }
 assert.deepEqual(pageErrors, []);
 console.log("PASS real browser E2E: goal, plans, validation, conflicts, reload, mobile, machine access and revocation");
} catch (error) {
 console.error("Browser errors:", pageErrors);
 console.error("Visible plan:", await page.locator(".goal-plans").innerText().catch(() => "no plan panel"));
 throw error;
} finally { await context.close(); await browser.close(); }
